# SPDX-License-Identifier: MPL-2.0
name: OSSF Scorecard

on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  scorecard:
    uses: hyperpolymath/standards/.github/workflows/scorecard-reusable.yml@257869d3061d5a8ed1529bf34225d90a2416d51a
    permissions:
      contents: read
      security-events: write
      id-token: write
